name: Feature request [IMAGE]
description: Suggest an idea for the Exegol IMAGE environment
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Verification before publication:

        - You are creating a feature request in the Exegol **IMAGE** repository (the exegol environment)! 
        > If your request concerns the exegol command specific to the Exegol **WRAPPER**, please open your issue on the [Exegol](https://github.com/ThePorgs/Exegol) repository
        - Check that there is not already your feature request on the Exegol **roadmap** (can be consulted in the **documentation** or on the Exegol **Discord**)


  - type: textarea
    attributes:
      label: The needs
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
