#!/bin/bash

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export SHELL=/bin/zsh

export XKL_XMODMAP_DISABLE=1
export XDG_SESSION_TYPE=x11

export XDG_RUNTIME_DIR=$(mktemp -d -t desktop-XXXXXX)
mkdir -p $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR

/etc/X11/Xsession

rm -rf $XDG_RUNTIME_DIR