on:
  workflow_call:
    inputs:
      SUPPORTED_ARCH:
        required: true
        type: string

jobs:
  exec:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
    uses: ./.github/workflows/building.yml
    with:
      ARCH: ${{ matrix.arch }}
      DOCKER_BUILD_REPO: " "
      IMAGE_BASE_NAME: " "
      DOCKERFILE: " "
    secrets:
      DOCKER_USERNAME: ""
      DOCKER_PASSWORD: ""
