on:
  workflow_call:
    inputs:
      DOCKER_BUILD_REPO:
        required: true
        type: string
      IMAGE_BASE_NAME:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
      ARCH:
        required: true
        type: string

jobs:
  setup:
    runs-on: self-hosted
    steps:
      -
        id: set-matrix
        name: "Debug inputs"
        run: |
          echo ${{ inputs.SUPPORTED_ARCH }}

  exec:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.SUPPORTED_ARCH) }}
    uses: ./.github/workflows/building.yml
    with:
      ARCH: ${{ matrix.arch }}
      DOCKER_BUILD_REPO: " "
      IMAGE_BASE_NAME: " "
      DOCKERFILE: " "
    secrets:
      DOCKER_USERNAME: ""
      DOCKER_PASSWORD: ""
