name: bug poc

on:
  push:
    branches:
      - cicd

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      data: ${{ steps.set-matrix.outputs.data }}
    steps:
      -
        id: set-matrix
        name: "Setup output"
        run: |
          echo "data={\"include\":[{\"arch\":\"amd64\"},{\"arch\":\"arm64\"}]}"
          echo "data={\"include\":[{\"arch\":\"amd64\"},{\"arch\":\"arm64\"}]}" >> $GITHUB_OUTPUT

  exec:
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.data) }}
      # matrix: ${{ fromJson('{"include":[{"arch":"amd64"},{"arch":"arm64"}') }}
         #arch: ${{ fromJson('["amd64","arm64"]') }}
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          echo ${{ matrix.arch }}
