# Pinned GitHub Actions
# - peter-evans/repository-dispatch v2 @ bf47d102fdb849e755b0b0023ea3e81a44b6f570
#   - Repo: https://github.com/peter-evans/repository-dispatch
#   - Version: https://github.com/peter-evans/repository-dispatch/tree/v2
#   - Pinned: https://github.com/peter-evans/repository-dispatch/commit/bf47d102fdb849e755b0b0023ea3e81a44b6f570
name: Release Build Trigger

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*b*"

jobs:
  trigger-private-pipeline:
    name: Trigger pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pipeline Repo
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570
        with:
          token: ${{ secrets.PIPELINE_PAT }}
          repository: ThePorgs/Pipelines
          event-type: release-pipeline
          client-payload: |
            {
              "version": "${{ github.ref_name }}"
            }