# Pinned GitHub Actions
# - actions/checkout v4 @ 34e114876b0b11c390a56381ad16ebd13914f8d5
#   - Repo: https://github.com/actions/checkout
#   - Version: https://github.com/actions/checkout/tree/v4
#   - Pinned: https://github.com/actions/checkout/commit/34e114876b0b11c390a56381ad16ebd13914f8d5
# - peter-evans/repository-dispatch v2 @ bf47d102fdb849e755b0b0023ea3e81a44b6f570
#   - Repo: https://github.com/peter-evans/repository-dispatch
#   - Version: https://github.com/peter-evans/repository-dispatch/tree/v2
#   - Pinned: https://github.com/peter-evans/repository-dispatch/commit/bf47d102fdb849e755b0b0023ea3e81a44b6f570
name: Nightly Build Trigger

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**.md"

jobs:
  trigger-private-pipeline:
    name: Trigger pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Get latest commit title (first line only)
        id: get_commit_title
        run: |
          raw_title="$(git log -1 --pretty=%B | head -n 1)"
          # Remove any potential dangerous characters
          sanitized_title=$(echo "$raw_title" | tr -cd '[:print:]\n')
          echo "commit_title=$sanitized_title" >> "$GITHUB_OUTPUT"

      - name: Trigger Pipeline Repo
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570
        # passing the title only, as a multi-line string is not supported
        with:
          token: ${{ secrets.PIPELINE_PAT }}
          repository: ThePorgs/Pipelines
          event-type: build-pipeline
          client-payload: |
            {
              "sha": "${{ github.sha }}",
              "commit_message": "${{ steps.get_commit_title.outputs.commit_title }}" 
            }