name: Pre-release (building base)

on:
  pull_request:
    title:
      - "Release *.*.*"
      - "Release *.*.*b*"
    branches: refacto2
    paths-ignore:
#      - ".github/**"
      - "**.md"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"