name: Debug (pr2) build

on:
  pull_request:
    title:
      - "Release *.*.*"
      - "Release *.*.*b*"
    branches: refacto2
    paths-ignore:
#      - ".github/**"
      - "**.md"

# cf https://github.com/actions/runner/issues/2324, paths-ignore will only be respected at PR creation
# all new commits then added in the PR will trigger the workflow

env:
  # intermediary registry in which architecture-specific images and base images must be pushed
  DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"

  # final registry target, in which arch-specific images must be aggregated
  DOCKER_TARGET_REPO: "nwodtuhs/exegol-dev-preprod"
  IMAGE_BASE_NAME: "debugpr1"
  # final dockerfile
  DOCKERFILE: "./sources/dockerfiles/debug.dockerfile"

  # ThePorgs/Exegol-docs branch for tools lists
  DOCS_TARGET_BRANCH: "dev-images"

  # exegol-base registry target
  DOCKER_TARGET_REPO_BASE: "nwodtuhs/exegol-base"
  # base.dockerfile, will build exegol-base, which will be used as initial layer for the other images
  DOCKERFILE_BASE: "./sources/dockerfiles/base.dockerfile"

jobs:
  # https://github.com/orgs/community/discussions/26671, "can’t pass ENV variables to the reusable workflow"
  start_workflow:
    name: Start preprod workflow
    strategy:
      fail-fast: false
      matrix:
        image_name: [ "debugprnested1", "debugprnested2", "debugprnested3" ]
    uses: ./.github/workflows/sub_entrypoint_preprod_debug.yml
    with:
      IMAGE_BASE_NAME: ${{ matrix.image_name }}
