name: Release LIGHT

on:
  push:
    tags:
      - '*'

jobs:
  release_image:
    name: Preparing
    uses: ./.github/workflows/full_build.yml
    with:
      DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
      DOCKER_TARGET_REPO: "nwodtuhs/exegol-preprod"
      IMAGE_BASE_NAME: light
      DOCKERFILE: "light.dockerfile"
      IMAGE_VERSION: ${{ github.ref_name }}
      SUPPORTED_ARCH: '["amd64","arm64"]'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
