name: Dev release NIGHTLY

on:
  push:
    branches:
      - dev

jobs:
  building_debug:
    name: Preparing
    uses: ./.github/workflows/full_build.yml
    with:
      DOCKER_BUILD_REPO: "nwodtuhs/exegol-builds"
      DOCKER_TARGET_REPO: "nwodtuhs/exegol"
      IMAGE_BASE_NAME: "nightly"
      DOCKERFILE: "Dockerfile"
      SUPPORTED_ARCH: '["amd64","arm64"]'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
